### ISSUE TITLE
robot_localization

### ISSUE THREAD

**Issue by zheng-xiao** [eliabntt/active_v_slam#3]
Hi, I have the new issue. Can you help me one more time? Thanks
fatal error: robot_localization/SetPose.h: No such file or directory
 #include "robot_localization/SetPose.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/zxn/dev/active_slam_v/src/active_v_slam-master/src/robotino_mpc/include/nlmpc.h:27:0,
                 from /home/zxn/dev/active_slam_v/src/active_v_slam-master/src/robotino_mpc/src/nlmpc.cpp:5:
/home/zxn/dev/active_slam_v/src/active_v_slam-master/src/robotino_fsm/include/robotino_fsm_node.h:26:10: fatal error: robot_localization/SetPose.h: No such file or directory
 #include "robot_localization/SetPose.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by eliabntt** [comment]
you are missing dependencies. Please follow the readme. that is related to the pkg robot_localization.
